In [1]:
import numpy as np

In [2]:
in_Size = 16
kernal_size = 3
stride = 2
out_channel = 3
out_Size = (in_Size-kernal_size)//stride+1
input = np.arange(in_Size**2, dtype=float).reshape((in_Size,in_Size))
conv_input = np.zeros(((out_Size)**2, kernal_size**2))
out_Size

7

In [3]:
print("input.shape : ",input.shape,"\nconv_input.shape : " ,conv_input.shape, end="\n\n")
# print("-------------input----------------\n",input,"\n-------------conv_input----------------\n", res)

input.shape :  (16, 16) 
conv_input.shape :  (49, 9)



In [4]:
for i in range(out_Size):
    for j in range(out_Size):
        for k in range(kernal_size):
            for l in range(kernal_size):
                if (k+i*stride < in_Size) and (l+j*stride < in_Size): 
                    conv_input[i*(out_Size)+j][k*kernal_size+l] = input[k+i*stride][l+j*stride] 
                    #만약 [k+i*stride][l+j*stride] 가 N보다 크면 걍 값에 0 때리면 됨.
                else:
                    conv_input[i*(out_Size)+j][k*kernal_size+l] = 0

In [5]:
conv_input[:30]

array([[  0.,   1.,   2.,  16.,  17.,  18.,  32.,  33.,  34.],
       [  2.,   3.,   4.,  18.,  19.,  20.,  34.,  35.,  36.],
       [  4.,   5.,   6.,  20.,  21.,  22.,  36.,  37.,  38.],
       [  6.,   7.,   8.,  22.,  23.,  24.,  38.,  39.,  40.],
       [  8.,   9.,  10.,  24.,  25.,  26.,  40.,  41.,  42.],
       [ 10.,  11.,  12.,  26.,  27.,  28.,  42.,  43.,  44.],
       [ 12.,  13.,  14.,  28.,  29.,  30.,  44.,  45.,  46.],
       [ 32.,  33.,  34.,  48.,  49.,  50.,  64.,  65.,  66.],
       [ 34.,  35.,  36.,  50.,  51.,  52.,  66.,  67.,  68.],
       [ 36.,  37.,  38.,  52.,  53.,  54.,  68.,  69.,  70.],
       [ 38.,  39.,  40.,  54.,  55.,  56.,  70.,  71.,  72.],
       [ 40.,  41.,  42.,  56.,  57.,  58.,  72.,  73.,  74.],
       [ 42.,  43.,  44.,  58.,  59.,  60.,  74.,  75.,  76.],
       [ 44.,  45.,  46.,  60.,  61.,  62.,  76.,  77.,  78.],
       [ 64.,  65.,  66.,  80.,  81.,  82.,  96.,  97.,  98.],
       [ 66.,  67.,  68.,  82.,  83.,  84.,  98.,  99.,

In [6]:
kernel = np.arange(kernal_size**2 * out_channel).reshape(out_channel, kernal_size**2)
kernel.shape

(3, 9)

In [7]:
# res, kernel
out = np.matmul(kernel, conv_input.T)
out.shape

(3, 49)

In [8]:
print(out.reshape((3, out_Size, out_Size)))

[[[  906.   978.  1050.  1122.  1194.  1266.  1338.]
  [ 2058.  2130.  2202.  2274.  2346.  2418.  2490.]
  [ 3210.  3282.  3354.  3426.  3498.  3570.  3642.]
  [ 4362.  4434.  4506.  4578.  4650.  4722.  4794.]
  [ 5514.  5586.  5658.  5730.  5802.  5874.  5946.]
  [ 6666.  6738.  6810.  6882.  6954.  7026.  7098.]
  [ 7818.  7890.  7962.  8034.  8106.  8178.  8250.]]

 [[ 2283.  2517.  2751.  2985.  3219.  3453.  3687.]
  [ 6027.  6261.  6495.  6729.  6963.  7197.  7431.]
  [ 9771. 10005. 10239. 10473. 10707. 10941. 11175.]
  [13515. 13749. 13983. 14217. 14451. 14685. 14919.]
  [17259. 17493. 17727. 17961. 18195. 18429. 18663.]
  [21003. 21237. 21471. 21705. 21939. 22173. 22407.]
  [24747. 24981. 25215. 25449. 25683. 25917. 26151.]]

 [[ 3660.  4056.  4452.  4848.  5244.  5640.  6036.]
  [ 9996. 10392. 10788. 11184. 11580. 11976. 12372.]
  [16332. 16728. 17124. 17520. 17916. 18312. 18708.]
  [22668. 23064. 23460. 23856. 24252. 24648. 25044.]
  [29004. 29400. 29796. 30192. 30588. 3098

In [9]:
import torch
import torch.nn as nn
t_out = torch.tensor(input.reshape(1, in_Size, in_Size), dtype=torch.float)
# t_ls

In [10]:
with torch.no_grad():
    conv1 = nn.Conv2d(1, 3, kernal_size, stride, dtype=torch.float, bias=False)
    print(conv1.weight.shape)
    val = 0
    for i in range(conv1.weight.shape[0]):
        for j in range(conv1.weight.shape[2]):
            for k in range(conv1.weight.shape[3]):
                conv1.weight[i][0][j][k] = val
                val+=1
                # print(conv1.weight[i][0][j][k])
print(conv1(t_out))

torch.Size([3, 1, 3, 3])
tensor([[[  906.,   978.,  1050.,  1122.,  1194.,  1266.,  1338.],
         [ 2058.,  2130.,  2202.,  2274.,  2346.,  2418.,  2490.],
         [ 3210.,  3282.,  3354.,  3426.,  3498.,  3570.,  3642.],
         [ 4362.,  4434.,  4506.,  4578.,  4650.,  4722.,  4794.],
         [ 5514.,  5586.,  5658.,  5730.,  5802.,  5874.,  5946.],
         [ 6666.,  6738.,  6810.,  6882.,  6954.,  7026.,  7098.],
         [ 7818.,  7890.,  7962.,  8034.,  8106.,  8178.,  8250.]],

        [[ 2283.,  2517.,  2751.,  2985.,  3219.,  3453.,  3687.],
         [ 6027.,  6261.,  6495.,  6729.,  6963.,  7197.,  7431.],
         [ 9771., 10005., 10239., 10473., 10707., 10941., 11175.],
         [13515., 13749., 13983., 14217., 14451., 14685., 14919.],
         [17259., 17493., 17727., 17961., 18195., 18429., 18663.],
         [21003., 21237., 21471., 21705., 21939., 22173., 22407.],
         [24747., 24981., 25215., 25449., 25683., 25917., 26151.]],

        [[ 3660.,  4056.,  4452.,

In [28]:
A = np.arange(2*3*32*32).reshape((2, 3, 32, 32))
B = np.arange(2*3*32*4).reshape((2, 3, 32, 4))

In [30]:
np.matmul(A, B).shape

(2, 3, 32, 4)