In [1]:
import numpy as np

In [260]:
N = 16
kernal_size = 2
stride = 2
out_N = (N-kernal_size)//stride+1
ls = np.arange(N**2, dtype=float).reshape((N,N))
res = np.zeros((((N-kernal_size)//stride+1)**2, kernal_size**2))

In [261]:
ls, res

(array([[  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
          11.,  12.,  13.,  14.,  15.],
        [ 16.,  17.,  18.,  19.,  20.,  21.,  22.,  23.,  24.,  25.,  26.,
          27.,  28.,  29.,  30.,  31.],
        [ 32.,  33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,
          43.,  44.,  45.,  46.,  47.],
        [ 48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,
          59.,  60.,  61.,  62.,  63.],
        [ 64.,  65.,  66.,  67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,
          75.,  76.,  77.,  78.,  79.],
        [ 80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,  89.,  90.,
          91.,  92.,  93.,  94.,  95.],
        [ 96.,  97.,  98.,  99., 100., 101., 102., 103., 104., 105., 106.,
         107., 108., 109., 110., 111.],
        [112., 113., 114., 115., 116., 117., 118., 119., 120., 121., 122.,
         123., 124., 125., 126., 127.],
        [128., 129., 130., 131., 132., 133., 134., 135., 136., 137., 138.,
     

In [262]:
for i in range((N-kernal_size)//stride+1):
# for i in range(2):
    for j in range((N-kernal_size)//stride+1):
        for k in range(kernal_size):
            for l in range(kernal_size):
                if (k+i*stride < N) and (l+j*stride < N): 
                    res[i*((N-kernal_size)//stride+1)+j][k*kernal_size+l] = ls[k+i*stride][l+j*stride] #만약 [k+i*stride][l+j*stride] 가 N보다 크면 걍 값에 0 때리면 됨.
                else:
                    res[i*((N-kernal_size)//stride+1)+j][k*kernal_size+l] = 0

In [263]:
res[:30]

array([[  0.,   1.,  16.,  17.],
       [  2.,   3.,  18.,  19.],
       [  4.,   5.,  20.,  21.],
       [  6.,   7.,  22.,  23.],
       [  8.,   9.,  24.,  25.],
       [ 10.,  11.,  26.,  27.],
       [ 12.,  13.,  28.,  29.],
       [ 14.,  15.,  30.,  31.],
       [ 32.,  33.,  48.,  49.],
       [ 34.,  35.,  50.,  51.],
       [ 36.,  37.,  52.,  53.],
       [ 38.,  39.,  54.,  55.],
       [ 40.,  41.,  56.,  57.],
       [ 42.,  43.,  58.,  59.],
       [ 44.,  45.,  60.,  61.],
       [ 46.,  47.,  62.,  63.],
       [ 64.,  65.,  80.,  81.],
       [ 66.,  67.,  82.,  83.],
       [ 68.,  69.,  84.,  85.],
       [ 70.,  71.,  86.,  87.],
       [ 72.,  73.,  88.,  89.],
       [ 74.,  75.,  90.,  91.],
       [ 76.,  77.,  92.,  93.],
       [ 78.,  79.,  94.,  95.],
       [ 96.,  97., 112., 113.],
       [ 98.,  99., 114., 115.],
       [100., 101., 116., 117.],
       [102., 103., 118., 119.],
       [104., 105., 120., 121.],
       [106., 107., 122., 123.]])

In [264]:
kernel = np.arange(12).reshape((1, 3, 4, 1))
kernel

array([[[[ 0],
         [ 1],
         [ 2],
         [ 3]],

        [[ 4],
         [ 5],
         [ 6],
         [ 7]],

        [[ 8],
         [ 9],
         [10],
         [11]]]])

In [265]:
# res, kernel
np.matmul(res, kernel).shape

(1, 3, 64, 1)

In [266]:
print(np.matmul(res, kernel).reshape((3, out_N, out_N)))

[[[  84.   96.  108.  120.  132.  144.  156.  168.]
  [ 276.  288.  300.  312.  324.  336.  348.  360.]
  [ 468.  480.  492.  504.  516.  528.  540.  552.]
  [ 660.  672.  684.  696.  708.  720.  732.  744.]
  [ 852.  864.  876.  888.  900.  912.  924.  936.]
  [1044. 1056. 1068. 1080. 1092. 1104. 1116. 1128.]
  [1236. 1248. 1260. 1272. 1284. 1296. 1308. 1320.]
  [1428. 1440. 1452. 1464. 1476. 1488. 1500. 1512.]]

 [[ 220.  264.  308.  352.  396.  440.  484.  528.]
  [ 924.  968. 1012. 1056. 1100. 1144. 1188. 1232.]
  [1628. 1672. 1716. 1760. 1804. 1848. 1892. 1936.]
  [2332. 2376. 2420. 2464. 2508. 2552. 2596. 2640.]
  [3036. 3080. 3124. 3168. 3212. 3256. 3300. 3344.]
  [3740. 3784. 3828. 3872. 3916. 3960. 4004. 4048.]
  [4444. 4488. 4532. 4576. 4620. 4664. 4708. 4752.]
  [5148. 5192. 5236. 5280. 5324. 5368. 5412. 5456.]]

 [[ 356.  432.  508.  584.  660.  736.  812.  888.]
  [1572. 1648. 1724. 1800. 1876. 1952. 2028. 2104.]
  [2788. 2864. 2940. 3016. 3092. 3168. 3244. 3320.]
  [4004.

In [267]:
import torch
import torch.nn as nn
t_ls = torch.tensor(ls.reshape(1, N, N), dtype=torch.float)
t_ls

tensor([[[  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
           11.,  12.,  13.,  14.,  15.],
         [ 16.,  17.,  18.,  19.,  20.,  21.,  22.,  23.,  24.,  25.,  26.,
           27.,  28.,  29.,  30.,  31.],
         [ 32.,  33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,
           43.,  44.,  45.,  46.,  47.],
         [ 48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,
           59.,  60.,  61.,  62.,  63.],
         [ 64.,  65.,  66.,  67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,
           75.,  76.,  77.,  78.,  79.],
         [ 80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,  89.,  90.,
           91.,  92.,  93.,  94.,  95.],
         [ 96.,  97.,  98.,  99., 100., 101., 102., 103., 104., 105., 106.,
          107., 108., 109., 110., 111.],
         [112., 113., 114., 115., 116., 117., 118., 119., 120., 121., 122.,
          123., 124., 125., 126., 127.],
         [128., 129., 130., 131., 132., 133., 134., 135., 136., 

In [268]:
with torch.no_grad():
    conv1 = nn.Conv2d(1, 3, kernal_size, stride, dtype=torch.float)
    print(conv1.weight.shape)
    val = 0
    for i in range(conv1.weight.shape[0]):
        for j in range(conv1.weight.shape[2]):
            for k in range(conv1.weight.shape[3]):
                conv1.weight[i][0][j][k] = val
                val+=1
                # print(conv1.weight[i][0][j][k])
print(conv1(t_ls))

torch.Size([3, 1, 2, 2])
tensor([[[  84.3608,   96.3608,  108.3608,  120.3608,  132.3608,  144.3608,
           156.3608,  168.3608],
         [ 276.3608,  288.3608,  300.3608,  312.3608,  324.3608,  336.3608,
           348.3608,  360.3608],
         [ 468.3608,  480.3608,  492.3608,  504.3608,  516.3608,  528.3608,
           540.3608,  552.3608],
         [ 660.3608,  672.3608,  684.3608,  696.3608,  708.3608,  720.3608,
           732.3608,  744.3608],
         [ 852.3608,  864.3608,  876.3608,  888.3608,  900.3608,  912.3608,
           924.3608,  936.3608],
         [1044.3607, 1056.3607, 1068.3607, 1080.3607, 1092.3607, 1104.3607,
          1116.3607, 1128.3607],
         [1236.3607, 1248.3607, 1260.3607, 1272.3607, 1284.3607, 1296.3607,
          1308.3607, 1320.3607],
         [1428.3607, 1440.3607, 1452.3607, 1464.3607, 1476.3607, 1488.3607,
          1500.3607, 1512.3607]],

        [[ 219.7895,  263.7895,  307.7895,  351.7895,  395.7895,  439.7895,
           483.7895,  527