In [9]:
import torch

A = torch.arange(2*3*4*5).reshape(5, 4, 2, 3)
A = A[2]
A

tensor([[[48, 49, 50],
         [51, 52, 53]],

        [[54, 55, 56],
         [57, 58, 59]],

        [[60, 61, 62],
         [63, 64, 65]],

        [[66, 67, 68],
         [69, 70, 71]]])

In [8]:
torch.einsum('c w h-> h w c',A)

tensor([[[[  0,  24,  48,  72,  96],
          [  6,  30,  54,  78, 102],
          [ 12,  36,  60,  84, 108],
          [ 18,  42,  66,  90, 114]],

         [[  3,  27,  51,  75,  99],
          [  9,  33,  57,  81, 105],
          [ 15,  39,  63,  87, 111],
          [ 21,  45,  69,  93, 117]]],


        [[[  1,  25,  49,  73,  97],
          [  7,  31,  55,  79, 103],
          [ 13,  37,  61,  85, 109],
          [ 19,  43,  67,  91, 115]],

         [[  4,  28,  52,  76, 100],
          [ 10,  34,  58,  82, 106],
          [ 16,  40,  64,  88, 112],
          [ 22,  46,  70,  94, 118]]],


        [[[  2,  26,  50,  74,  98],
          [  8,  32,  56,  80, 104],
          [ 14,  38,  62,  86, 110],
          [ 20,  44,  68,  92, 116]],

         [[  5,  29,  53,  77, 101],
          [ 11,  35,  59,  83, 107],
          [ 17,  41,  65,  89, 113],
          [ 23,  47,  71,  95, 119]]]])

In [3]:
L = torch.Tensor(3, 5, 4, 2) # (1 3 2 0)
for i in range(A.shape[0]):
    for j in range(A.shape[1]):
        for k in range(A.shape[2]):
            for l in range(A.shape[3]):
                L[j][l][k][i] = A[i][j][k][l]
L.flatten()

tensor([  0.,  60.,   5.,  65.,  10.,  70.,  15.,  75.,   1.,  61.,   6.,  66.,
         11.,  71.,  16.,  76.,   2.,  62.,   7.,  67.,  12.,  72.,  17.,  77.,
          3.,  63.,   8.,  68.,  13.,  73.,  18.,  78.,   4.,  64.,   9.,  69.,
         14.,  74.,  19.,  79.,  20.,  80.,  25.,  85.,  30.,  90.,  35.,  95.,
         21.,  81.,  26.,  86.,  31.,  91.,  36.,  96.,  22.,  82.,  27.,  87.,
         32.,  92.,  37.,  97.,  23.,  83.,  28.,  88.,  33.,  93.,  38.,  98.,
         24.,  84.,  29.,  89.,  34.,  94.,  39.,  99.,  40., 100.,  45., 105.,
         50., 110.,  55., 115.,  41., 101.,  46., 106.,  51., 111.,  56., 116.,
         42., 102.,  47., 107.,  52., 112.,  57., 117.,  43., 103.,  48., 108.,
         53., 113.,  58., 118.,  44., 104.,  49., 109.,  54., 114.,  59., 119.])

In [4]:

A_dim = [2, 3, 4, 5]
A_stride = [60, 20, 5, 1]

L_dim = [3, 5, 4, 2]
L_stride = [ 40, 8, 2, 1]
ch_inx = [1, 3, 2, 0]
tmp_inx = [3, 0, 2, 1]

In [5]:
V = A.reshape(-1)
L = torch.Tensor((120))
for inx in range(len(V)):# ten->T 전체의 넓이
    new_inx = 0
    tmp = inx
    for i in range(len(A_dim)): # dim_num
        print((tmp // A_stride[i]),"*",L_stride[ch_inx[i]],end=" ")
        new_inx += (tmp // A_stride[i]) * L_stride[tmp_inx[i]]
        tmp %= A_stride[i]

    print(new_inx)
    L[new_inx] = V[inx]
    

0 * 8 0 * 1 0 * 2 0 * 40 0
0 * 8 0 * 1 0 * 2 1 * 40 8
0 * 8 0 * 1 0 * 2 2 * 40 16
0 * 8 0 * 1 0 * 2 3 * 40 24
0 * 8 0 * 1 0 * 2 4 * 40 32
0 * 8 0 * 1 1 * 2 0 * 40 2
0 * 8 0 * 1 1 * 2 1 * 40 10
0 * 8 0 * 1 1 * 2 2 * 40 18
0 * 8 0 * 1 1 * 2 3 * 40 26
0 * 8 0 * 1 1 * 2 4 * 40 34
0 * 8 0 * 1 2 * 2 0 * 40 4
0 * 8 0 * 1 2 * 2 1 * 40 12
0 * 8 0 * 1 2 * 2 2 * 40 20
0 * 8 0 * 1 2 * 2 3 * 40 28
0 * 8 0 * 1 2 * 2 4 * 40 36
0 * 8 0 * 1 3 * 2 0 * 40 6
0 * 8 0 * 1 3 * 2 1 * 40 14
0 * 8 0 * 1 3 * 2 2 * 40 22
0 * 8 0 * 1 3 * 2 3 * 40 30
0 * 8 0 * 1 3 * 2 4 * 40 38
0 * 8 1 * 1 0 * 2 0 * 40 40
0 * 8 1 * 1 0 * 2 1 * 40 48
0 * 8 1 * 1 0 * 2 2 * 40 56
0 * 8 1 * 1 0 * 2 3 * 40 64
0 * 8 1 * 1 0 * 2 4 * 40 72
0 * 8 1 * 1 1 * 2 0 * 40 42
0 * 8 1 * 1 1 * 2 1 * 40 50
0 * 8 1 * 1 1 * 2 2 * 40 58
0 * 8 1 * 1 1 * 2 3 * 40 66
0 * 8 1 * 1 1 * 2 4 * 40 74
0 * 8 1 * 1 2 * 2 0 * 40 44
0 * 8 1 * 1 2 * 2 1 * 40 52
0 * 8 1 * 1 2 * 2 2 * 40 60
0 * 8 1 * 1 2 * 2 3 * 40 68
0 * 8 1 * 1 2 * 2 4 * 40 76
0 * 8 1 * 1 3 * 2 0 * 40 

In [6]:
L

tensor([  0.,  60.,   5.,  65.,  10.,  70.,  15.,  75.,   1.,  61.,   6.,  66.,
         11.,  71.,  16.,  76.,   2.,  62.,   7.,  67.,  12.,  72.,  17.,  77.,
          3.,  63.,   8.,  68.,  13.,  73.,  18.,  78.,   4.,  64.,   9.,  69.,
         14.,  74.,  19.,  79.,  20.,  80.,  25.,  85.,  30.,  90.,  35.,  95.,
         21.,  81.,  26.,  86.,  31.,  91.,  36.,  96.,  22.,  82.,  27.,  87.,
         32.,  92.,  37.,  97.,  23.,  83.,  28.,  88.,  33.,  93.,  38.,  98.,
         24.,  84.,  29.,  89.,  34.,  94.,  39.,  99.,  40., 100.,  45., 105.,
         50., 110.,  55., 115.,  41., 101.,  46., 106.,  51., 111.,  56., 116.,
         42., 102.,  47., 107.,  52., 112.,  57., 117.,  43., 103.,  48., 108.,
         53., 113.,  58., 118.,  44., 104.,  49., 109.,  54., 114.,  59., 119.])