In [10]:
import torch
num_tokens = 16
model_dim = 8
x_input = 8
torch.cuda.is_available()

True

In [11]:
Q = (0.01 * torch.arange(0, x_input * model_dim, 1)).reshape(x_input, model_dim)
K = (0.01 * torch.arange(0, x_input * model_dim, 1)).reshape(x_input, model_dim)
V = (0.01 * torch.arange(0, x_input * model_dim, 1)).reshape(x_input, model_dim)

In [12]:
Q

tensor([[0.0000, 0.0100, 0.0200, 0.0300, 0.0400, 0.0500, 0.0600, 0.0700],
        [0.0800, 0.0900, 0.1000, 0.1100, 0.1200, 0.1300, 0.1400, 0.1500],
        [0.1600, 0.1700, 0.1800, 0.1900, 0.2000, 0.2100, 0.2200, 0.2300],
        [0.2400, 0.2500, 0.2600, 0.2700, 0.2800, 0.2900, 0.3000, 0.3100],
        [0.3200, 0.3300, 0.3400, 0.3500, 0.3600, 0.3700, 0.3800, 0.3900],
        [0.4000, 0.4100, 0.4200, 0.4300, 0.4400, 0.4500, 0.4600, 0.4700],
        [0.4800, 0.4900, 0.5000, 0.5100, 0.5200, 0.5300, 0.5400, 0.5500],
        [0.5600, 0.5700, 0.5800, 0.5900, 0.6000, 0.6100, 0.6200, 0.6300]])

In [14]:
X = (0.01 * torch.arange(0, num_tokens * model_dim, 1)).reshape(num_tokens, model_dim)
Q = torch.matmul(X, Q)
K = torch.matmul(X, K)
V = torch.matmul(X, V)
S = torch.matmul(Q, K.T)

In [17]:
V

tensor([[0.1120, 0.1148, 0.1176, 0.1204, 0.1232, 0.1260, 0.1288, 0.1316],
        [0.2912, 0.3004, 0.3096, 0.3188, 0.3280, 0.3372, 0.3464, 0.3556],
        [0.4704, 0.4860, 0.5016, 0.5172, 0.5328, 0.5484, 0.5640, 0.5796],
        [0.6496, 0.6716, 0.6936, 0.7156, 0.7376, 0.7596, 0.7816, 0.8036],
        [0.8288, 0.8572, 0.8856, 0.9140, 0.9424, 0.9708, 0.9992, 1.0276],
        [1.0080, 1.0428, 1.0776, 1.1124, 1.1472, 1.1820, 1.2168, 1.2516],
        [1.1872, 1.2284, 1.2696, 1.3108, 1.3520, 1.3932, 1.4344, 1.4756],
        [1.3664, 1.4140, 1.4616, 1.5092, 1.5568, 1.6044, 1.6520, 1.6996],
        [1.5456, 1.5996, 1.6536, 1.7076, 1.7616, 1.8156, 1.8696, 1.9236],
        [1.7248, 1.7852, 1.8456, 1.9060, 1.9664, 2.0268, 2.0872, 2.1476],
        [1.9040, 1.9708, 2.0376, 2.1044, 2.1712, 2.2380, 2.3048, 2.3716],
        [2.0832, 2.1564, 2.2296, 2.3028, 2.3760, 2.4492, 2.5224, 2.5956],
        [2.2624, 2.3420, 2.4216, 2.5012, 2.5808, 2.6604, 2.7400, 2.8196],
        [2.4416, 2.5276, 2.6136, 2.699

In [8]:
Q.shape, K.shape, V.shape, X.shape

(torch.Size([16, 8]),
 torch.Size([16, 8]),
 torch.Size([16, 8]),
 torch.Size([16, 8]))

In [5]:
S.shape

torch.Size([16, 16])

In [6]:
S

tensor([[ 0.1190,  0.3162,  0.5134,  0.7106,  0.9078,  1.1050,  1.3022,  1.4994,
          1.6965,  1.8937,  2.0909,  2.2881,  2.4853,  2.6825,  2.8797,  3.0769],
        [ 0.3162,  0.8403,  1.3643,  1.8884,  2.4124,  2.9365,  3.4605,  3.9846,
          4.5086,  5.0327,  5.5567,  6.0808,  6.6048,  7.1289,  7.6529,  8.1770],
        [ 0.5134,  1.3643,  2.2152,  3.0661,  3.9170,  4.7680,  5.6189,  6.4698,
          7.3207,  8.1716,  9.0225,  9.8734, 10.7244, 11.5753, 12.4262, 13.2771],
        [ 0.7106,  1.8884,  3.0661,  4.2439,  5.4217,  6.5995,  7.7772,  8.9550,
         10.1328, 11.3106, 12.4883, 13.6661, 14.8439, 16.0216, 17.1994, 18.3772],
        [ 0.9078,  2.4124,  3.9170,  5.4217,  6.9263,  8.4310,  9.9356, 11.4402,
         12.9449, 14.4495, 15.9541, 17.4588, 18.9634, 20.4680, 21.9727, 23.4773],
        [ 1.1050,  2.9365,  4.7680,  6.5995,  8.4310, 10.2624, 12.0939, 13.9254,
         15.7569, 17.5884, 19.4199, 21.2514, 23.0829, 24.9144, 26.7459, 28.5774],
        [ 1.3022,  3.4

In [18]:
S = torch.nn.Softmax()(S)
O = torch.matmul(S, V)

/tmp/ipykernel_16846/684408600.py:1: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  S = torch.nn.Softmax()(S)


In [19]:
O

tensor([[2.1056, 2.1796, 2.2536, 2.3276, 2.4016, 2.4756, 2.5496, 2.6236],
        [2.5405, 2.6300, 2.7196, 2.8091, 2.8986, 2.9882, 3.0777, 3.1672],
        [2.6664, 2.7605, 2.8545, 2.9485, 3.0426, 3.1366, 3.2306, 3.3247],
        [2.7203, 2.8162, 2.9122, 3.0081, 3.1041, 3.2000, 3.2960, 3.3919],
        [2.7488, 2.8458, 2.9428, 3.0398, 3.1367, 3.2337, 3.3307, 3.4276],
        [2.7658, 2.8634, 2.9610, 3.0586, 3.1561, 3.2537, 3.3513, 3.4489],
        [2.7766, 2.8746, 2.9725, 3.0705, 3.1685, 3.2664, 3.3644, 3.4623],
        [2.7837, 2.8819, 2.9802, 3.0784, 3.1766, 3.2748, 3.3730, 3.4712],
        [2.7885, 2.8869, 2.9853, 3.0837, 3.1821, 3.2805, 3.3789, 3.4773],
        [2.7919, 2.8904, 2.9889, 3.0874, 3.1859, 3.2844, 3.3829, 3.4815],
        [2.7942, 2.8928, 2.9914, 3.0900, 3.1886, 3.2872, 3.3858, 3.4844],
        [2.7959, 2.8945, 2.9932, 3.0918, 3.1905, 3.2891, 3.3878, 3.4864],
        [2.7970, 2.8957, 2.9944, 3.0931, 3.1918, 3.2905, 3.3892, 3.4879],
        [2.7979, 2.8966, 2.9953, 3.094