In [1]:
# import torch
# from torchvision import datasets, transforms

# transform = transforms.Compose([transforms.ToTensor()])
# train_dataset = datasets.MNIST(root='./data', train=True, download=True, transform=transform)
# test_dataset = datasets.MNIST(root='./data', train=False, download=True, transform=transform)

# x_train = train_dataset.data.float()
# x_test = test_dataset.data.float()

# # padding
# def pad_batches(data, batch_size):
#     pad_size = (-len(data)) % batch_size
#     if pad_size > 0:
#         data = torch.nn.functional.pad(data, (0, 0, 0, 0, 0, pad_size))
#     return data

# x_train_padded = pad_batches(x_train, 4)
# x_test_padded = pad_batches(x_test, 4)

# # batch -> 4
# x_train_batches = x_train_padded.view(-1, 4, 28, 28)
# x_test_batches = x_test_padded.view(-1, 4, 28, 28)

# # 이진 파일로
# x_train_bat
# ('mnist_train_batches_fp32.bin')
# x_test_batches.numpy().tofile('mnist_test_batches_fp32.bin')

# print("Binary files have been saved.")



In [2]:
import torch
A_dim = [4,3, 2, 4]
B_dim = [3, 5, 2]
A_mult = 1
B_mult = 1
for i in A_dim:
    A_mult *= i
for i in B_dim:
    B_mult *= i


A = torch.arange(A_mult).reshape(*A_dim)
B = torch.arange(B_mult).reshape(*B_dim)

In [3]:
B

tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7],
         [ 8,  9]],

        [[10, 11],
         [12, 13],
         [14, 15],
         [16, 17],
         [18, 19]],

        [[20, 21],
         [22, 23],
         [24, 25],
         [26, 27],
         [28, 29]]])

In [4]:
A = torch.Tensor([[[[1,2],[5,6]]], [[[9,10],[13,14]]], [[[17,18],[21,22]]]]).to(torch.long)
torch.matmul(B, A)
# A.shape


tensor([[[[   5,    6],
          [  17,   22],
          [  29,   38],
          [  41,   54],
          [  53,   70]],

         [[  65,   86],
          [  77,  102],
          [  89,  118],
          [ 101,  134],
          [ 113,  150]],

         [[ 125,  166],
          [ 137,  182],
          [ 149,  198],
          [ 161,  214],
          [ 173,  230]]],


        [[[  13,   14],
          [  57,   62],
          [ 101,  110],
          [ 145,  158],
          [ 189,  206]],

         [[ 233,  254],
          [ 277,  302],
          [ 321,  350],
          [ 365,  398],
          [ 409,  446]],

         [[ 453,  494],
          [ 497,  542],
          [ 541,  590],
          [ 585,  638],
          [ 629,  686]]],


        [[[  21,   22],
          [  97,  102],
          [ 173,  182],
          [ 249,  262],
          [ 325,  342]],

         [[ 401,  422],
          [ 477,  502],
          [ 553,  582],
          [ 629,  662],
          [ 705,  742]],

         [[ 781,  82

In [5]:
torch.matmul(A, B)

RuntimeError: Expected size for first two dimensions of batch2 tensor to be: [9, 2] but got: [9, 5].

In [ ]:
mat_inx = 20

dimA = [5, 1, 2, 3]
dimB = [4, 3, 2]
dimC = [5, 4, 2, 2]
strideA = [6, 6, 3, 1]
strideB = [6, 2, 1]
strideC = [16, 4, 2, 1]

inx = mat_inx * strideC[len(strideC)-3]

inxA = 0
inxB = 0
inx_tmp = inx
cont = len(strideA) - len(strideB)
inxC = 4*[0]

for i in range(len(strideA)-2):
    inxC[i] = inx_tmp // strideC[i]
    if dimA[i] != 1:
        inxA += (inx_tmp // strideC[i]) * strideA[i]
    inx_tmp %= strideC[i]
print(inxC)
inxA

[5, 0, 0, 0]


30

In [ ]:
mat_inx+=1

dimA = [5, 1, 2, 3]
dimB = [4, 3, 2]
dimC = [5, 4, 2, 2]
strideA = [6, 6, 3, 1]
strideB = [6, 2, 1]
strideC = [16, 4, 2, 1]

inx = mat_inx * strideC[len(strideC)-3]

inxA = 0
inxB = 0
inx_tmp = inx
cont = len(strideA) - len(strideB)

inxC = 4*[0]
for i in range(cont):
    inxC[i] = inx_tmp // strideC[i]
    if dimA[i] != 1:
        inxA += (inx_tmp // strideC[i]) * strideA[i]
    inx_tmp %= strideC[i]

for i in range(cont, len(strideA)-2):
    inxC[i] = inx_tmp // strideC[i]
    if dimA[i] != 1:
        inxA += (inx_tmp // strideC[i]) * strideA[i]
    if dimB[i-cont] != 1:
        inxB += (inx_tmp // strideC[i]) * strideB[i-cont]
    inx_tmp %= strideC[i]
print(inxC)
inxA, inxB

[5, 2, 0, 0]


(30, 12)

In [ ]:
import torch
A = torch.arange(1*2*3*4).reshape(*dimA)
B = torch.arange(4*3*2).reshape(*dimB)

In [ ]:
torch.matmul(A, B)

tensor([[[[  10,   13],
          [  28,   40]],

         [[  28,   31],
          [ 100,  112]],

         [[  46,   49],
          [ 172,  184]],

         [[  64,   67],
          [ 244,  256]]],


        [[[  46,   67],
          [  64,   94]],

         [[ 172,  193],
          [ 244,  274]],

         [[ 298,  319],
          [ 424,  454]],

         [[ 424,  445],
          [ 604,  634]]],


        [[[  82,  121],
          [ 100,  148]],

         [[ 316,  355],
          [ 388,  436]],

         [[ 550,  589],
          [ 676,  724]],

         [[ 784,  823],
          [ 964, 1012]]],


        [[[ 118,  175],
          [ 136,  202]],

         [[ 460,  517],
          [ 532,  598]],

         [[ 802,  859],
          [ 928,  994]],

         [[1144, 1201],
          [1324, 1390]]],


        [[[ 154,  229],
          [ 172,  256]],

         [[ 604,  679],
          [ 676,  760]],

         [[1054, 1129],
          [1180, 1264]],

         [[1504, 1579],
          [1684, 1

In [65]:
import torch

A = list()

for j in range(3):
    A_ = list()
    for i in range(j*70, j*70+ 57, 14):
        A_.append(torch.arange(i, i+5, 1))
    A.append(torch.stack(A_))
A = torch.stack(A)
A

tensor([[[  0,   1,   2,   3,   4],
         [ 14,  15,  16,  17,  18],
         [ 28,  29,  30,  31,  32],
         [ 42,  43,  44,  45,  46],
         [ 56,  57,  58,  59,  60]],

        [[ 70,  71,  72,  73,  74],
         [ 84,  85,  86,  87,  88],
         [ 98,  99, 100, 101, 102],
         [112, 113, 114, 115, 116],
         [126, 127, 128, 129, 130]],

        [[140, 141, 142, 143, 144],
         [154, 155, 156, 157, 158],
         [168, 169, 170, 171, 172],
         [182, 183, 184, 185, 186],
         [196, 197, 198, 199, 200]]])

In [66]:
B = torch.arange(25).reshape(5, 5)
B

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]])

In [68]:
torch.matmul(B, A)

tensor([[[  420,   430,   440,   450,   460],
         [ 1120,  1155,  1190,  1225,  1260],
         [ 1820,  1880,  1940,  2000,  2060],
         [ 2520,  2605,  2690,  2775,  2860],
         [ 3220,  3330,  3440,  3550,  3660]],

        [[ 1120,  1130,  1140,  1150,  1160],
         [ 3570,  3605,  3640,  3675,  3710],
         [ 6020,  6080,  6140,  6200,  6260],
         [ 8470,  8555,  8640,  8725,  8810],
         [10920, 11030, 11140, 11250, 11360]],

        [[ 1820,  1830,  1840,  1850,  1860],
         [ 6020,  6055,  6090,  6125,  6160],
         [10220, 10280, 10340, 10400, 10460],
         [14420, 14505, 14590, 14675, 14760],
         [18620, 18730, 18840, 18950, 19060]]])

In [6]:
import torch 
import torch.nn as nn

nn.Sequential(
    nn.Linear(784, 50),
    nn.Linear(50, 30),
    nn.Linear(30, 40),
    nn.Linear(40, 10)
)

Sequential(
  (0): Linear(in_features=784, out_features=50, bias=True)
  (1): Linear(in_features=50, out_features=30, bias=True)
  (2): Linear(in_features=30, out_features=40, bias=True)
  (3): Linear(in_features=40, out_features=10, bias=True)
)