In [2]:
import timm
import torch
import torch.nn as nn
import numpy as np

In [3]:
from timm.data import resolve_data_config
from timm.data.transforms_factory import create_transform
model = timm.create_model('vit_base_patch16_224', pretrained=True)

config = resolve_data_config({}, model=model)
transform = create_transform(**config)

In [4]:
# dc = model.named_children()
# dc = list(dc)
# x = torch.arange(4*3*224*224, dtype=torch.float32).reshape(4, 3, 224, 224)
# x.shape

## block WEIGHT binaryfile 생성


In [5]:
for layer in range(12):
    block = dict(dict(dict(model.named_children())['blocks'].named_children())[str(layer)].named_children())
    ls = [block['norm1'],list(block['attn'].children())[0], list(block['attn'].children())[4],block['norm2'],list(block['mlp'].children())[0], list(block['mlp'].children())[4]]

    weight_ls = list()
    for i in range(len(ls)):
        weight_ls.append(ls[i].weight.clone().detach().numpy().T)
        weight_ls.append(ls[i].bias.clone().detach().numpy())

    blk_weight = np.array(weight_ls[0].flatten())

    for i in range(1, len(weight_ls)):
        blk_weight = np.concatenate((blk_weight, weight_ls[i].flatten()))
    blk_weight.tofile('./pre_weights/'+str(layer)+'_newblock'+'.bin')

### QKV WEIGHT BINFILE

In [6]:
layer = 0
dd = dict(list(list(model.named_children())[4][1].children())[layer].named_children())
blk = dict(dd['attn'].named_children())

## dummy input check

In [7]:
torch.manual_seed(10)
dummy_input = torch.randn((4, 196, 768))
qkv_w = dict(dd['attn'].named_children())['qkv'].weight.clone().detach().T

In [8]:
# dummy_input.numpy().tofile('./pre_weights/dummy_input_4_196_768.bin')

In [9]:
dummy_input.shape

torch.Size([4, 196, 768])

In [10]:
blocks = list()
for layer in range(12):
    block = dict(dict(dict(model.named_children())['blocks'].named_children())[str(layer)].named_children())
    ls = [list(block['attn'].children())[0], list(block['attn'].children())[4],list(block['mlp'].children())[0], list(block['mlp'].children())[4]]

    weight_ls = list()
    for i in range(len(ls)):
        weight_ls.append(ls[i].weight.clone().detach().T)
        weight_ls.append(ls[i].bias.clone().detach())
    blocks.append(weight_ls)

    

for i in blocks[0]:
    print(i.shape)
    

torch.Size([768, 2304])
torch.Size([2304])
torch.Size([768, 768])
torch.Size([768])
torch.Size([768, 3072])
torch.Size([3072])
torch.Size([3072, 768])
torch.Size([768])


# FLASH ATTENTION VALUE CHECK

In [11]:
block = dict(dict(dict(model.named_children())['blocks'].named_children())[str(layer)].named_children())
# Fetch correct qkv weights and biases from the block
qkv_layer = dict(block['attn'].named_children())['qkv']
qkv_weights = qkv_layer.weight  # Shape: (out_features, in_features)
qkv_bias = qkv_layer.bias

# Transpose qkv_weights to shape (in_features, out_features) for matrix multiplication
qkv_weights = qkv_weights.T  # Now shape: (in_features, out_features)

# Apply the QKV linear projection with the correct transposed weights and biases
dQKV = torch.add(torch.matmul(dummy_input, qkv_weights), qkv_bias)

# Reshape and permute to get the correct multi-head attention format
dQKV = dQKV.view(4, 196, 12, 3, 64)  # (batch, seq_len, num_heads, qkv, head_dim)
dQKV = torch.einsum('b p h k d -> b h k p d', dQKV)  # Permute dimensions

# Calculate attention manually for each head
Os = list()
for i in range(12):
    Q = dQKV[0][i][0]  # Query for head i
    K = dQKV[0][i][1]  # Key for head i
    V = dQKV[0][i][2]  # Value for head i
    
    # Apply scaled dot-product attention with numerical stability
    attn_weights = torch.matmul(Q, K.T) / (Q.size(-1) ** 0.5)  # Scale by sqrt(d_k)
    attn_weights = attn_weights - torch.max(attn_weights, dim=-1, keepdim=True)[0]  # Numerical stability
    attn_weights = torch.nn.functional.softmax(attn_weights, dim=-1)
    
    O = torch.matmul(attn_weights, V)  # Multiply attention weights by V
    Os.append(O)

# Concatenate outputs from all heads and apply the projection layer
concat_Os = torch.cat(Os, dim=1)  # Concatenate along the feature dimension (head outputs)
proj_output = dict(block['attn'].named_children())['proj'](concat_Os)[:8, :8]  # Apply projection layer
proj_output

tensor([[-0.2055, -0.1736,  0.4550,  0.2223, -0.0058, -0.1951,  0.1081, -0.0950],
        [-0.2403, -0.1827,  0.3924,  0.2354, -0.0299, -0.1278,  0.1057, -0.0935],
        [-0.2598, -0.1673,  0.4965,  0.2337, -0.0930, -0.1645,  0.0652, -0.0784],
        [-0.2632, -0.1369,  0.4431,  0.2356,  0.0452, -0.1379,  0.0822, -0.0350],
        [-0.2474, -0.1771,  0.3949,  0.1860,  0.0159, -0.1896,  0.0057, -0.0729],
        [-0.2212, -0.1546,  0.4233,  0.1712, -0.0062, -0.1302,  0.0796, -0.0667],
        [-0.2667, -0.1787,  0.4048,  0.2312,  0.0124, -0.1626,  0.1034, -0.1029],
        [-0.2447, -0.1572,  0.4262,  0.2408,  0.0147, -0.1515,  0.0910, -0.0736]],
       grad_fn=<SliceBackward0>)

In [12]:
blk1 = blocks[0]
torch.manual_seed(10)
blk1[0] = blk1[0].to(torch.float32)
blk1[1] = blk1[1].to(torch.float32)

dummy_input = torch.randn((4, 196, 768), dtype=torch.float32)
print(torch.matmul(dummy_input,blk1[0])[0][0][1])
dQKV = torch.add(torch.matmul(dummy_input,blk1[0]), blk1[1])
dQKV = dQKV.view(4, 196, 3, 12, 64)
dQKV = torch.einsum('b p k h d -> k b h p d',dQKV)
dQKV.shape

tensor(-1.1279)


torch.Size([3, 4, 12, 196, 64])

In [13]:
Qs, Ks, Vs = dQKV.unbind(0)

4 : batch
12 : Multi head
3 : QKV

In [14]:
Q = Qs[0][0]# batch head
K = Ks[0][0]
V = Vs[0][0]

In [15]:
# torch.matmul(torch.nn.functional.softmax(torch.matmul(Q, K.T), dim=1),V)[188:196,8:16]#일반 ATTN
torch.matmul(torch.nn.functional.softmax(torch.matmul(Q, K.T), dim=1),V).shape#일반 ATTN

torch.Size([196, 64])

In [16]:
Os = list()
for i in range(12):
    Q = Qs[0][i]# batch head
    K = Ks[0][i]
    V = Vs[0][i]
    O = torch.matmul(torch.nn.functional.softmax(torch.matmul(Q, K.T)/8, dim=1),V)
    Os.append(O)
torch.concat(Os, dim=1)[:8,:8]
dict(block['attn'].named_children())['proj'](torch.concat(Os, dim=1))[:8,:8]


tensor([[ 0.0201,  0.1241,  0.2855, -0.2697, -0.2250,  0.6140, -0.0903, -0.4683],
        [ 0.5427, -0.0843,  0.0165, -0.2499, -0.4020,  0.5875, -0.0717, -0.6233],
        [ 0.0990, -0.1040,  0.1056, -0.0610, -0.2217,  0.2057, -0.0635, -0.3588],
        [ 0.3024, -0.0653, -0.0542, -0.2307, -0.2722,  0.1737, -0.0037, -0.5988],
        [ 0.0938,  0.0728,  0.3319, -0.3459, -0.2872,  0.4283,  0.2563, -0.3149],
        [ 0.1920, -0.0805,  0.0075, -0.2601, -0.2883,  0.2606, -0.1216, -0.2211],
        [ 0.2577, -0.0885,  0.0766, -0.2594, -0.2453,  0.4059,  0.0835, -0.2692],
        [ 0.3502, -0.3796,  0.2173, -0.5175, -0.1211,  0.9736,  0.1606, -0.3987]],
       grad_fn=<SliceBackward0>)

In [28]:
layer = 0
block = dict(dict(dict(model.named_children())['blocks'].named_children())[str(layer)].named_children())
# list(block['attn'].children())[0]
ls = [list(block['attn'].children())[0], list(block['attn'].children())[4],list(block['mlp'].children())[0], list(block['mlp'].children())[4]]
ls[0]
block['attn']
print(torch.round((block['attn'](dummy_input))[2,188:,760:]*1000)/1000)
# torch.round(dict(dict(model.named_children())['blocks'].named_children())[str(0)](dummy_input)[0,:8,:8]*100)/100
block

tensor([[ 0.1160,  0.0130,  0.1180,  0.0090, -0.0920, -0.2190,  0.1030,  0.2480],
        [ 0.2220, -0.0080, -0.1670,  0.0520, -0.0000, -0.0100, -0.0760,  0.3100],
        [ 0.1020, -0.0650,  0.1430,  0.0320, -0.0640, -0.2800,  0.0630,  0.3230],
        [ 0.0510,  0.0880, -0.0770,  0.2210,  0.0650, -0.2940,  0.0600,  0.1930],
        [ 0.0970, -0.0080,  0.1480, -0.0320, -0.0160, -0.2480,  0.1040,  0.0700],
        [ 0.1160, -0.1060,  0.1930,  0.0130,  0.0290, -0.1590,  0.1320,  0.1870],
        [ 0.0990, -0.0990,  0.0100, -0.0660, -0.0790, -0.1010,  0.1420, -0.0100],
        [ 0.1710, -0.0330,  0.1460, -0.1300, -0.1790, -0.2540,  0.1940,  0.0700]],
       grad_fn=<DivBackward0>)


{'norm1': LayerNorm((768,), eps=1e-06, elementwise_affine=True),
 'attn': Attention(
   (qkv): Linear(in_features=768, out_features=2304, bias=True)
   (q_norm): Identity()
   (k_norm): Identity()
   (attn_drop): Dropout(p=0.0, inplace=False)
   (proj): Linear(in_features=768, out_features=768, bias=True)
   (proj_drop): Dropout(p=0.0, inplace=False)
 ),
 'ls1': Identity(),
 'drop_path1': Identity(),
 'norm2': LayerNorm((768,), eps=1e-06, elementwise_affine=True),
 'mlp': Mlp(
   (fc1): Linear(in_features=768, out_features=3072, bias=True)
   (act): GELU(approximate='none')
   (drop1): Dropout(p=0.0, inplace=False)
   (norm): Identity()
   (fc2): Linear(in_features=3072, out_features=768, bias=True)
   (drop2): Dropout(p=0.0, inplace=False)
 ),
 'ls2': Identity(),
 'drop_path2': Identity()}

In [18]:
block['attn']

Attention(
  (qkv): Linear(in_features=768, out_features=2304, bias=True)
  (q_norm): Identity()
  (k_norm): Identity()
  (attn_drop): Dropout(p=0.0, inplace=False)
  (proj): Linear(in_features=768, out_features=768, bias=True)
  (proj_drop): Dropout(p=0.0, inplace=False)
)