In [3]:
import timm
import torch
import torch.nn as nn
import numpy as np

In [4]:
from timm.data import resolve_data_config
from timm.data.transforms_factory import create_transform

model = timm.create_model('vit_base_patch16_224', pretrained=True)

config = resolve_data_config({}, model=model)
transform = create_transform(**config)

In [6]:
torch.manual_seed(10)
dummy_input = torch.randn((4, 196, 768))

In [7]:
X = dummy_input.reshape(4, 14, 14, 3, 16, 16).permute(0, 3, 1, 4, 2, 5).reshape(4, 3, 224, 224)
model(X)[:,18:25]

tensor([[3.5802, 1.8354, 1.5026, 5.7265, 4.8261, 4.7573, 1.8068],
        [3.0854, 1.6711, 1.2817, 5.1313, 3.9568, 4.0316, 1.9193],
        [3.5101, 1.8066, 1.5194, 5.2364, 4.4752, 4.3399, 2.1460],
        [3.3423, 1.6898, 1.4246, 5.4188, 4.6331, 4.4577, 1.9496]],
       grad_fn=<SliceBackward0>)

# embedd, 마지막 norm, head

In [6]:
wembed = dict(dict(model.named_children())['patch_embed'].named_children())['proj'].weight.detach().clone().reshape(768,-1)
print(wembed.shape)
print(wembed.reshape(768,-1).shape)
embed_bias = dict(dict(model.named_children())['patch_embed'].named_children())['proj'].bias.detach()


dummy_image = dummy_input.reshape(4, 14, 14, 3, 16, 16).permute(0, 3, 1, 4, 2, 5).reshape(4,3,224, 224)
print(dict(dict(model.named_children())['patch_embed'].named_children())['proj'](dummy_image).reshape(4, 768 ,-1).permute(0, 2, 1)[0,:4,:4])
(torch.matmul(dummy_input, wembed.T) + embed_bias)[0,:4,:4]
# dummy_input.shape, wembed.shape

torch.Size([768, 768])
torch.Size([768, 768])
tensor([[ 9.6483e-02, -9.3246e-02, -6.8695e-02, -2.1101e-02],
        [ 7.9544e-02,  2.4428e-01, -9.4195e-02, -4.2136e-02],
        [ 8.8661e-02,  7.0976e-01, -1.4698e-02, -7.3706e-02],
        [ 1.9149e-01,  1.3783e+00,  4.4599e-04,  1.8156e-01]],
       grad_fn=<SliceBackward0>)


tensor([[ 9.6483e-02, -9.3246e-02, -6.8695e-02, -2.1101e-02],
        [ 7.9544e-02,  2.4428e-01, -9.4195e-02, -4.2136e-02],
        [ 8.8661e-02,  7.0976e-01, -1.4698e-02, -7.3706e-02],
        [ 1.9149e-01,  1.3783e+00,  4.4600e-04,  1.8156e-01]])

0. patch_embed_weight (768,768)
1. patch_embed_bias     (768,)
2. cls_token            (768)
3. pos_embed            (197, 768)
3. end_norm_weight      (768,)
4. end_norm_bias        (768,)
5. end_head_weight      (768,1000)
6. end_head_bias        (1000)

In [14]:
#  'norm': LayerNorm((768,), eps=1e-06, elementwise_affine=True),
#  'fc_norm': Identity(),
#  'head_drop': Dropout(p=0.0, inplace=False),
#  'head': Linear(in_features=768, out_features=1000, bias=True)
# dict(model.named_children())

extra_weight = list()
print(dict(dict(model.named_children())['patch_embed'].named_children())['proj'])
extra_weight.append(dict(dict(model.named_children())['patch_embed'].named_children())['proj'].weight.detach().clone().reshape(768,-1).mT.numpy())
extra_weight.append(dict(dict(model.named_children())['patch_embed'].named_children())['proj'].bias.detach().clone().numpy())
print("cls : ", model.cls_token.shape)
extra_weight.append(model.cls_token.detach().clone().numpy())
print("pos embedding : ",model.pos_embed.shape)
extra_weight.append(model.pos_embed.detach().clone().numpy())
print(dict(model.named_children())['norm'])
extra_weight.append(dict(model.named_children())['norm'].weight.detach().clone().numpy())
extra_weight.append(dict(model.named_children())['norm'].bias.detach().clone().numpy())
print(dict(model.named_children())['head'])
extra_weight.append(dict(model.named_children())['head'].weight.detach().clone().mT.numpy())
extra_weight.append(dict(model.named_children())['head'].bias.detach().clone().numpy())

extra_weight_bin = extra_weight[0].flatten()
print(extra_weight_bin.shape)
for i in range(1,len(extra_weight)):
    print(extra_weight_bin.shape," + ",extra_weight[i].shape)
    extra_weight_bin = np.concatenate([extra_weight_bin, extra_weight[i].flatten()])
extra_weight_bin.tofile('./pre_weights/extra_weights'+'.bin')
# np.round(extra_weight[0][:8,:8]*1000)/1000

Conv2d(3, 768, kernel_size=(16, 16), stride=(16, 16))
cls :  torch.Size([1, 1, 768])
pos embedding :  torch.Size([1, 197, 768])
LayerNorm((768,), eps=1e-06, elementwise_affine=True)
Linear(in_features=768, out_features=1000, bias=True)
(589824,)
(589824,)  +  (768,)
(590592,)  +  (1, 1, 768)
(591360,)  +  (1, 197, 768)
(742656,)  +  (768,)
(743424,)  +  (768,)
(744192,)  +  (768, 1000)
(1512192,)  +  (1000,)


In [22]:
print(torch.round(model.pos_embed[0,:8,:8]*100)/100)

tensor([[ 0.3100,  0.0400, -0.4600, -0.0200,  0.5400,  0.3700,  0.0900, -0.0000],
        [ 0.0200,  0.0000, -1.2500, -0.0700,  0.0500,  0.1000,  0.1300,  0.0000],
        [-0.0300,  0.0100, -2.0000, -0.2200, -0.1300,  0.1700, -0.2600,  0.0100],
        [-0.0100,  0.0000, -1.5900, -0.0900, -0.0300,  0.1000, -0.1700,  0.0100],
        [-0.0100,  0.0000, -1.1700, -0.0800, -0.1600,  0.1000, -0.1900,  0.0100],
        [ 0.0200, -0.0000, -0.3500, -0.1600, -0.1200, -0.1000,  0.0100,  0.0000],
        [ 0.0400,  0.0000,  0.5600, -0.1200, -0.0500,  0.0600,  0.1900,  0.0000],
        [ 0.0700, -0.0000,  0.8800, -0.0700, -0.1100,  0.0500,  0.3200,  0.0000]],
       grad_fn=<DivBackward0>)


In [24]:
dict(model.named_children())['norm'].weight[:8]

tensor([2.7612, 2.8031, 2.7742, 2.6937, 2.7796, 2.8239, 2.7704, 2.7019],
       grad_fn=<SliceBackward0>)

In [11]:
layer = 0
dd = dict(list(list(model.named_children())[4][1].children())[layer].named_children())
blk = dict(dd['attn'].named_children())
list(model.named_children())[4][1](dummy_input)[0,:8,:8]
# out = list(list(model.named_children())[4][1].children())[layer](dummy_input)
# print(torch.round(out[0,:8,:8]*100)/100)

tensor([[ 0.0280, -2.3828, -1.3331, -0.6497,  2.6020, -3.7639,  1.3410,  2.1520],
        [ 1.5410, -1.6672,  0.3384,  0.3190,  2.2647, -4.3770, -1.1260,  0.7224],
        [ 1.0063, -2.2873, -3.0505, -0.4749,  3.1893, -3.6413, -1.2599, -0.8521],
        [ 1.4777, -2.7316, -2.4451,  0.1806,  4.0741, -5.2172,  0.4056,  0.4105],
        [ 1.9599, -0.5510, -1.5149, -0.4525,  2.0296, -1.9757,  0.4506,  0.4652],
        [ 2.6184, -1.4111, -1.7321,  1.6008,  3.6662, -1.4856,  0.5681, -0.0500],
        [ 1.4040, -2.0944, -1.1621,  0.2040,  3.5855, -4.7889, -1.2848,  0.3293],
        [ 1.1181, -1.5272, -1.2754, -1.3712,  2.9798, -3.4699, -0.8871, -0.2288]],
       grad_fn=<SliceBackward0>)

In [20]:
layer = 0
block = dict(dict(dict(model.named_children())['blocks'].named_children())[str(layer)].named_children())
# list(block['attn'].children())[0]
ls = [list(block['attn'].children())[0], list(block['attn'].children())[4],list(block['mlp'].children())[0], list(block['mlp'].children())[4]]
ls[0].weight.clone().detach().numpy().T

array([[ 7.2626420e-03, -2.9949723e-03,  9.4074765e-03, ...,
        -3.2589093e-03, -4.8755802e-04, -7.5052856e-05],
       [ 3.7414711e-03,  4.8236307e-03,  7.7275973e-04, ...,
         5.4976184e-02, -1.9960701e-02, -3.2710023e-02],
       [-7.1642242e-02,  9.2979968e-03,  8.8727295e-02, ...,
         2.6372870e-04,  8.2003663e-04,  1.5374532e-04],
       ...,
       [-1.5707944e-02, -4.2519234e-03, -6.4309017e-04, ...,
        -2.4189011e-03,  9.2029461e-04, -5.5038952e-04],
       [ 6.1580893e-03,  4.0107276e-03, -2.2229922e-04, ...,
        -3.4691595e-02, -1.6753733e-02, -4.1766364e-02],
       [-7.5428464e-02, -3.1640060e-02, -3.2658712e-03, ...,
        -1.0773140e-02, -5.7062814e-03, -8.2098795e-03]], dtype=float32)

In [21]:
layer = 0
block = dict(dict(dict(model.named_children())['blocks'].named_children())[str(layer)].named_children())
ls = [block['norm1'],list(block['attn'].children())[0], list(block['attn'].children())[4],block['norm2'],list(block['mlp'].children())[0], list(block['mlp'].children())[4]]

weight_ls = list()
for i in range(len(ls)):
    weight_ls.append(ls[i].weight.clone().detach().numpy().T)
    weight_ls.append(ls[i].bias.clone().detach().numpy())
for i in weight_ls:
    print(i.shape)

(768,)
(768,)
(768, 2304)
(2304,)
(768, 768)
(768,)
(768,)
(768,)
(768, 3072)
(3072,)
(3072, 768)
(768,)


In [30]:
for layer in range(12):
    block = dict(dict(dict(model.named_children())['blocks'].named_children())[str(layer)].named_children())
    ls = [block['norm1'],list(block['attn'].children())[0], list(block['attn'].children())[4],block['norm2'],list(block['mlp'].children())[0], list(block['mlp'].children())[4]]

    weight_ls = list()
    for i in range(len(ls)):
        weight_ls.append(ls[i].weight.clone().detach().numpy().T)
        weight_ls.append(ls[i].bias.clone().detach().numpy())

    print(weight_ls[0].flatten().shape)
    blk_weight = np.array(weight_ls[0].flatten())

    for i in range(1, len(weight_ls)):
        print(weight_ls[i].flatten().shape)
        blk_weight = np.concatenate((blk_weight, weight_ls[i].flatten()))
        print(blk_weight.shape, "\n")
    blk_weight.tofile('./pre_weights/'+str(layer)+'_newblock'+'.bin')

(768,)
(768,)
(1536,) 

(1769472,)
(1771008,) 

(2304,)
(1773312,) 

(589824,)
(2363136,) 

(768,)
(2363904,) 

(768,)
(2364672,) 

(768,)
(2365440,) 

(2359296,)
(4724736,) 

(3072,)
(4727808,) 

(2359296,)
(7087104,) 

(768,)
(7087872,) 

(768,)
(768,)
(1536,) 

(1769472,)
(1771008,) 

(2304,)
(1773312,) 

(589824,)
(2363136,) 

(768,)
(2363904,) 

(768,)
(2364672,) 

(768,)
(2365440,) 

(2359296,)
(4724736,) 

(3072,)
(4727808,) 

(2359296,)
(7087104,) 

(768,)
(7087872,) 

(768,)
(768,)
(1536,) 

(1769472,)
(1771008,) 

(2304,)
(1773312,) 

(589824,)
(2363136,) 

(768,)
(2363904,) 

(768,)
(2364672,) 

(768,)
(2365440,) 

(2359296,)
(4724736,) 

(3072,)
(4727808,) 

(2359296,)
(7087104,) 

(768,)
(7087872,) 

(768,)
(768,)
(1536,) 

(1769472,)
(1771008,) 

(2304,)
(1773312,) 

(589824,)
(2363136,) 

(768,)
(2363904,) 

(768,)
(2364672,) 

(768,)
(2365440,) 

(2359296,)
(4724736,) 

(3072,)
(4727808,) 

(2359296,)
(7087104,) 

(768,)
(7087872,) 

(768,)
(768,)
(1536,) 

(1769472,)
(

- norm1
- Wqkv
- proj
- norm2
- mlp1
- mlp2

<img src="./layer_norm.png" title="layernorm"/>

In [ ]:
weight_ls = list()
for i in range(len(ls)):
    weight_ls.append(ls[i].weight.clone().detach().numpy().T)
    weight_ls.append(ls[i].bias.clone().detach().numpy())

# qkv_w = qkv.weight.clone().detach().numpy().T
# qkv_w.tofile('./pre_weights/qkv_W_head_'+str(layer)+'.bin')
print(weight_ls[0].flatten().shape)
blk_weight = np.array(weight_ls[0].flatten())

for i in range(1, len(weight_ls)):
    print(weight_ls[i].flatten().shape)
    blk_weight = np.concatenate((blk_weight, weight_ls[i].flatten()))
    print(blk_weight.shape, "\n")
blk_weight.tofile('./pre_weights/'+str(layer)+'_block'+'.bin')